// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Dl155iJ7O07OwHKgYLnyp0Jx-hgCWbA',
    appId: '1:95940934033:web:3d9fd96a59a0ba1abbc230',
    messagingSenderId: '95940934033',
    projectId: 'chatapp-4908c',
    authDomain: 'chatapp-4908c.firebaseapp.com',
    storageBucket: 'chatapp-4908c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKGLf6ktPdVW622i0y54Pg6BeDoP1CH5I',
    appId: '1:95940934033:android:b4ef01bc16cacb2bbbc230',
    messagingSenderId: '95940934033',
    projectId: 'chatapp-4908c',
    storageBucket: 'chatapp-4908c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQRdx0UdpxhqhG6pqxCSpPt_tSyICcl_Y',
    appId: '1:95940934033:ios:2c092b9266a54040bbc230',
    messagingSenderId: '95940934033',
    projectId: 'chatapp-4908c',
    storageBucket: 'chatapp-4908c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQRdx0UdpxhqhG6pqxCSpPt_tSyICcl_Y',
    appId: '1:95940934033:ios:2c092b9266a54040bbc230',
    messagingSenderId: '95940934033',
    projectId: 'chatapp-4908c',
    storageBucket: 'chatapp-4908c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Dl155iJ7O07OwHKgYLnyp0Jx-hgCWbA',
    appId: '1:95940934033:web:94b5c2ff79005d28bbc230',
    messagingSenderId: '95940934033',
    projectId: 'chatapp-4908c',
    authDomain: 'chatapp-4908c.firebaseapp.com',
    storageBucket: 'chatapp-4908c.firebasestorage.app',
  );
}
